E-CartShopping/Controllers/ShoppingController.cs
using E_CartShopping.Models;
using E_CartShopping.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace E_CartShopping.Controllers
{
    public class ShoppingController : Controller
    {
        private ECartDBEntities objECartDBEntities;
        private List<ShoppingCartViewModel> listOfShoppingCartViewModels;
        public ShoppingController()
        {
            objECartDBEntities = new ECartDBEntities();
            listOfShoppingCartViewModels = new List<ShoppingCartViewModel>();
        }
        // GET: Shopping
        public ActionResult Index()
        {
            IEnumerable<ShoppingViewModel> ListOfShoppingViewModel = (from objItem in objECartDBEntities.Items
                                                                      join objCategory in objECartDBEntities.Categories
                                                                      on objItem.CategoryId equals objCategory.CategoryId
                                                                      select new ShoppingViewModel()
                                                                      {
                                                                          ImagePath = objItem.ImagePath,
                                                                          ItemName = objItem.ItemName,
                                                                          Description = objItem.Description,
                                                                          ItemPrice = objItem.ItemPrice,
                                                                          ItemId = objItem.ItemId,
                                                                          Category = objCategory.CategoryName

                                                                      }).ToList();

            return View(ListOfShoppingViewModel);
        }
        [HttpPost]
        public JsonResult Index(string ItemId)
        {
            ShoppingCartViewModel objShoppingCartViewModel = new ShoppingCartViewModel();

            Item objItem = objECartDBEntities.Items.Single(model => model.ItemId.ToString() == ItemId);

            if(Session["CartCounter"] != null)
            {
                listOfShoppingCartViewModels = Session["CartItem"] as List<ShoppingCartViewModel>;
            }

            if(listOfShoppingCartViewModels.Any(model => model.ItemId == ItemId))
            {
                objShoppingCartViewModel = listOfShoppingCartViewModels.Single(model => model.ItemId == ItemId);
                objShoppingCartViewModel.Quantity = objShoppingCartViewModel.Quantity + 1;
                objShoppingCartViewModel.Total = objShoppingCartViewModel.Quantity * objShoppingCartViewModel.UnitPrice;
            }
            else
            {
                objShoppingCartViewModel.ItemId = ItemId;
                objShoppingCartViewModel.ImagePath = objItem.ImagePath;
                objShoppingCartViewModel.ItemName = objItem.ItemName;
                objShoppingCartViewModel.Quantity = 1;
                objShoppingCartViewModel.UnitPrice = objItem.ItemPrice;
                objShoppingCartViewModel.Total = objItem.ItemPrice;

                listOfShoppingCartViewModels.Add(objShoppingCartViewModel);
            }

            Session["CartCounter"] = listOfShoppingCartViewModels.Count;
            Session["CartItem"] = listOfShoppingCartViewModels;

            return Json(new { success = true, counter = listOfShoppingCartViewModels.Count}, JsonRequestBehavior.AllowGet);
        }
        public ActionResult ShoppingCart()
        {
            listOfShoppingCartViewModels = Session["CartItem"] as List<ShoppingCartViewModel>;

            return View(listOfShoppingCartViewModels);
        }
        [HttpPost]
        public ActionResult AddOrder()
        {
            int OrderId = 0;
            listOfShoppingCartViewModels = Session["CartItem"] as List<ShoppingCartViewModel>;

            Order objOrder = new Order()
            {
                OrderDate = DateTime.Now,
                OrderNumber = String.Format("{0:ddMMyyyyHHmmss}", DateTime.Now)
            };

            objECartDBEntities.Orders.Add(objOrder);
            objECartDBEntities.SaveChanges();

            OrderId = objOrder.OrderId;

            foreach (var item in listOfShoppingCartViewModels)
            {
                OrderDetail objOrderDetail = new OrderDetail();
                objOrderDetail.Total = item.Total;
                objOrderDetail.ItemId = item.ItemId;
                objOrderDetail.OrderId = OrderId;
                objOrderDetail.Quantity = item.Quantity;
                objOrderDetail.UnitPrice = item.UnitPrice;

                objECartDBEntities.OrderDetails.Add(objOrderDetail);
                objECartDBEntities.SaveChanges();

            }

            Session["CartCounter"] = null;
            Session["CartItem"] = null;

            return RedirectToAction("Index");
        }
    }
}

E-CartShopping/Views/Shopping/Index.cshtml
@model IEnumerable<E_CartShopping.ViewModel.ShoppingViewModel>
@{
    ViewBag.Title = "Index";
}
@*<h2>ShoppingController Index</h2>*@
<style>
    #heading {
        margin: 20px;
        text-align: center;
    }
    .card {
        box-shadow: 5px 5px 15px -5px rgba(0, 0, 0, 0.5);
        border-radius: 2%;
        margin-bottom: 8px;
        border: none;
        background-color: white;
    }
    .card-img-top {
            height: 160px; 
            width: 220px;
            padding: 12px 0px 0px 40px;
    }
    .card-body {
        padding: 10px 0px 5px 30px;
    }
    #btnAddToCard {
            text-align: right; 
            margin-left: 15px;
    }
</style>
<script type="text/javascript">
    function AddToCart(item) {
        var itemId = $(item).attr("itemid");
        var formData = new FormData();
        formData.append("ItemId", itemId);

        $.ajax({
            async: true,
            type: 'POST',
            contentType: false,
            processData: false,
            data: formData,
            url: '/Shopping/Index',
            success: function (data) {
                if (data.success) {
                    $("#cartItem").text("Cart(" + data.counter + ")");
                }
            },
            error: function () {
                alert("There is some problem.")
            }
        });
    }
</script>
<div class="container">
    <h2 id="heading">Products List</h2>
    @foreach (var item in Model)
    {
        <div class="col-md-3 mb-5">
            <div class="card">
                <img class="card-img-top" src="@Url.Content(item.ImagePath)" alt="Card image cap" />
                <div class="card-body">
                    <h4 class="card-title">@item.ItemName</h4>
                    <p class="card-text">@item.Description</p>
                    <b>@item.ItemPrice.ToString("#,##0.00 INR")</b>
                    <input id="btnAddToCard" type="button" name="AddToCard" value="Add to Cart" class="btn btn-primary" itemid="@item.ItemId" onclick="AddToCart(this)" />
                </div>
            </div>
        </div>      
     }
</div>

E-CartShopping/Views/Shopping/ShoppingCart.cshtml
@model IEnumerable<E_CartShopping.ViewModel.ShoppingCartViewModel>
@{
    ViewBag.Title = "ShoppingCart";
    decimal TotalAmount = 0.00M;
}
@*<h2>ShoppingController ShoppingCart</h2>*@
<style>
    .container {
        margin-top: 20px;
    }

    tr:hover {
        background-color: #f5f5f5;
    }

    th {
        background-color: #4CAF50;
        color: white;
    }

    th, td {
        text-align: center;
    }
</style>

@using (Html.BeginForm("AddOrder", "Shopping", FormMethod.Post))
{
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <table class="table">
                <thead>
                    <tr>
                        <th>Item Image</th>
                        <th>Item Name</th>
                        <th>Quantity</th>
                        <th>Unit Price</th>
                        <th>Total Price</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        TotalAmount += item.Total;
                        <tr>
                            <td>
                                <img src="@Url.Content(item.ImagePath)" height="40px" width="40px" class="img-rounded" />
                            </td>
                            <td>@item.ItemName</td>
                            <td>@item.Quantity</td>
                            <td>@item.UnitPrice.ToString("#,##0.00")</td>
                            <td style="text-align: right; padding-right: 70px">@item.Total.ToString("#,##0.00")</td>
                        </tr>
                    }
                    <tr class="alert-success">
                        <td colspan="4" style="text-align: right">
                            <h4>Total Amount </h4>
                        </td>
                        <td style="text-align: right; padding-right: 40px">
                            <h4>@TotalAmount.ToString("#,##0.00")</h4>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-md-10" style="text-align: right">
            <input id="SaveOrder" type="submit" value="Save" name="Save" class="btn btn-primary" />
        </div>
    </div>
    <div class="row">
        <div style="text-align: center">
            @Html.ActionLink("Back to Shopping", "Index", "Shopping")
        </div>
    </div>
</div>
}